# Generated by Django 5.1 on 2024-08-25 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('description', models.TextField()),
                ('is_sold', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False)),
            ],
        ),
    ]
